services:
  - docker:dind

stages:
  - build
  - test

build-backend:
  image: docker:latest
  stage: build
  before_script:
    - echo "Build backend"
  script:
    - cd backend
    - docker build -t backend .
  after_script:
    - echo "Build okay"

build-frontend:
  image: docker:latest
  stage: build
  before_script:
    - echo "Build frontend"
  script:
    - cd frontend
    - docker build -t frontend .
  after_script:
    - echo "Build okay"

test-backend:
  image: docker/compose:latest
  stage: test
  before_script:
    - echo "Test backend"
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Test backend okay"

test-frontend:
  image: docker/compose:latest
  stage: test
  before_script:
    - echo ""
  script:
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Test frontend okay"
