services:
  - docker:dind

stages:     
  - build
  - test
  - deploy

build-backend:
  image: docker:latest
  stage: build
  before_script:
    - echo "Build backend"
  script:
    - cd backend
    - docker build -t backend .
  after_script:
    - echo "Build okay"

build-frontend:
  image: docker:latest
  stage: build
  before_script:
    - echo "Build frontend"
  script:
    - cd frontend
    - docker build -t frontend .
  after_script:
    - echo "Build okay"

test-backend:
  image: docker/compose:latest
  stage: test
  before_script:
    - echo "Test backend"
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Test backend okay"

test-frontend:
  image: docker/compose:latest
  stage: test
  before_script:
    - echo "Test frontend"
  script:
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Test frontend okay"

deploy-frontend:
  image: docker:latest
  stage: deploy
  before_script:
    - echo "Deploy front"
    - docker login -u $USER -p $PASSWORD
  script:
    - docker build -t $USER/trab-02-gces -f frontend/Dockerfile frontend
    - docker push $USER/trab-02-gces
  after_script:
    - echo "Deploy front okay"

deploy-backend:  
  image: docker:latest
  stage: deploy
  before_script:
    - echo "Deploy back"
    - docker login -u $USER -p $PASSWORD
  script:
    - docker build -t $USER/trab-02-gces-backend -f backend/Dockerfile backend
    - docker push  $USER/trab-02-gces-backend
  after_script:
    - echo "Deploy back okay"


