image: docker:latest

stages:          
  - build
  - test
  
build-backend:
  stage: build
  before_script:
    - echo "Build backend"
  script:
    - cd backend
    - docker build -t backend .
  after_script:
    - echo "Build okay"

build-frontend:
  stage: build
  before_script:
    - echo "Build frontend"
  script:
    - docker build -f frontend/Dockerfile frontend
  after_script:
    - echo "Build okay"

